# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Travelling Embassy of Rockall
email: team@rockall.is
description: > # this means to ignore newlines until "baseurl:"
  What if you could start a new society on a tiny island in the middle of the ocean?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rockall.is" # the base hostname & protocol for your site
twitter_username: RockallEmbassy
github_username:  rockall-festival

# Build settings
markdown: kramdown
